name: Auto Delete Old Workflow Runs

on:
  schedule:
    - cron: "0 16 * * 1" 
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7   
          keep_minimum_runs: 2  
